version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development

  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run storybook
    ports:
      - '6006:6006'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/storybook-static
    environment:
      NODE_ENV: development
